name: clean_code_training
description: Clean Code Training Project.

publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  clean_framework:
    git:
      url: git@github.com:MattHamburger/flutter_clean_framework.git
  go_router: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

assets:
  - test/features/pokemon/presentation/assets/bulbasaur.jpeg
  - test/features/pokemon/presentation/assets/ivysaur.jpeg
  - test/features/pokemon/presentation/assets/venusaur.jpeg